package br.sp.eml.projects.padariabythecode.secondscreens;

import br.sp.eml.projects.padariabythecode.dao.ClienteDAO;
import br.sp.eml.projects.padariabythecode.model.Cliente;
import br.sp.eml.projects.padariabythecode.utils.Validador;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author narum
 */
public class TelaEditarCadastroClientes extends javax.swing.JFrame {

    /**
     * Construtor da classe TelaEditarCadastroClientes. Inicializa os
     * componentes gráficos gerados automaticamente. Em seguida, define a
     * posição da janela ao centro da tela.
     */
    Cliente obj = null;

    public TelaEditarCadastroClientes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public TelaEditarCadastroClientes(Cliente objAlterar) {
        initComponents();
        setLocationRelativeTo(null);

        this.obj = objAlterar;

        lblCliente_ID.setText("ID: " + String.valueOf(obj.getIdCliente()));
        txtNomeCliente.setText(String.valueOf(obj.getNomeCliente()));
        txtCPFCliente.setText(String.valueOf(obj.getCpfCliente()));
        
//        txtDtNascimentoCliente.setText(String.valueOf(obj.getDataNascimentoCliente()));
        java.util.Date dataFormatada = new java.util.Date(objAlterar.getDataNascimentoCliente().getTime());
        
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        
        txtDtNascimentoCliente.setText(formatador.format(dataFormatada));    
        
        txtGeneroCliente.setText(String.valueOf(obj.getGeneroCliente()));
        txtEstadoCivilCliente.setText(String.valueOf(obj.getEstadoCivilCliente()));
        txtTelFixCliente.setText(String.valueOf(obj.getTelefoneCliente()));
        txtEmailCliente.setText(String.valueOf(obj.getEmailCliente()));
        txtCEPCliente.setText(String.valueOf(obj.getCepCliente()));
        txtLogCliente.setText(String.valueOf(obj.getLogradouroCliente()));
        txtNumCliente.setText(String.valueOf(obj.getNumeroCliente()));
        txtComplementoCliente.setText(String.valueOf(obj.getComplementoCliente()));
        txtBairroCliente.setText(String.valueOf(obj.getBairroCliente()));
        txtCidadeCliente.setText(String.valueOf(obj.getCidadeCliente()));
        cboUFCliente.setSelectedItem(String.valueOf(obj.getUfCliente()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadosBasicos = new javax.swing.JPanel();
        lblDadosBasicos = new javax.swing.JLabel();
        lblCliente_ID = new javax.swing.JLabel();
        lblCliente_CPF = new javax.swing.JLabel();
        txtCPFCliente = new javax.swing.JFormattedTextField();
        lblCliente_dtNasc = new javax.swing.JLabel();
        txtDtNascimentoCliente = new javax.swing.JFormattedTextField();
        lblCliente_Genero = new javax.swing.JLabel();
        txtGeneroCliente = new javax.swing.JTextField();
        lblCliente_EstCivil = new javax.swing.JLabel();
        txtEstadoCivilCliente = new javax.swing.JTextField();
        lblCliente_Nome = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblCliente_TelFixo = new javax.swing.JLabel();
        txtTelFixCliente = new javax.swing.JFormattedTextField();
        lblCliente_Email = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        pnlEndereco = new javax.swing.JPanel();
        lblCliente_End = new javax.swing.JLabel();
        lblCliente_CEP = new javax.swing.JLabel();
        txtCEPCliente = new javax.swing.JFormattedTextField();
        lblCliente_Log = new javax.swing.JLabel();
        txtLogCliente = new javax.swing.JTextField();
        lblCliente_Num = new javax.swing.JLabel();
        txtNumCliente = new javax.swing.JFormattedTextField();
        lblCliente_Compl = new javax.swing.JLabel();
        txtComplementoCliente = new javax.swing.JTextField();
        lblCliente_Bairro = new javax.swing.JLabel();
        txtBairroCliente = new javax.swing.JTextField();
        lblCliente_Cid = new javax.swing.JLabel();
        txtCidadeCliente = new javax.swing.JTextField();
        lblCliente_UF = new javax.swing.JLabel();
        cboUFCliente = new javax.swing.JComboBox<>();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Edição de Cadastro de Clientes");
        setResizable(false);

        pnlDadosBasicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDadosBasicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDadosBasicos.setText("Dados Básicos");

        lblCliente_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCliente_ID.setText("ID: 000");

        lblCliente_CPF.setText("CPF:");

        try {
            txtCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCPFCliente.setName("CPF"); // NOI18N

        lblCliente_dtNasc.setText("Data de Nascimento:");

        try {
            txtDtNascimentoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtNascimentoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDtNascimentoCliente.setName("Data de Nascimento"); // NOI18N

        lblCliente_Genero.setText("Gênero:");

        txtGeneroCliente.setName("Gênero"); // NOI18N
        txtGeneroCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGeneroClienteKeyTyped(evt);
            }
        });

        lblCliente_EstCivil.setText("Estado Civil:");

        txtEstadoCivilCliente.setName("Estado Civil"); // NOI18N
        txtEstadoCivilCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoCivilClienteActionPerformed(evt);
            }
        });
        txtEstadoCivilCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoCivilClienteKeyTyped(evt);
            }
        });

        lblCliente_Nome.setText("Nome do Cliente:");

        txtNomeCliente.setName("Nome do Cliente"); // NOI18N
        txtNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeClienteKeyTyped(evt);
            }
        });

        lblCliente_TelFixo.setText("Telefone Fixo:");

        try {
            txtTelFixCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelFixCliente.setName("Telefone Fixo"); // NOI18N

        lblCliente_Email.setText("E-mail:");

        txtEmailCliente.setName("Email"); // NOI18N
        txtEmailCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosBasicosLayout = new javax.swing.GroupLayout(pnlDadosBasicos);
        pnlDadosBasicos.setLayout(pnlDadosBasicosLayout);
        pnlDadosBasicosLayout.setHorizontalGroup(
            pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNomeCliente)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosBasicosLayout.createSequentialGroup()
                        .addComponent(lblDadosBasicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCliente_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosBasicosLayout.createSequentialGroup()
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCliente_CPF)
                            .addComponent(lblCliente_TelFixo)
                            .addComponent(txtCPFCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtTelFixCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                                .addComponent(lblCliente_Email)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCliente_dtNasc)
                                    .addComponent(txtDtNascimentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCliente_Genero)
                                    .addComponent(txtGeneroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                                        .addComponent(lblCliente_EstCivil)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtEstadoCivilCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                            .addComponent(txtEmailCliente)))
                    .addComponent(lblCliente_Nome, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosBasicosLayout.setVerticalGroup(
            pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosBasicosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCliente_ID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDadosBasicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCliente_Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                        .addComponent(lblCliente_CPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                        .addComponent(lblCliente_dtNasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtNascimentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente_Genero)
                            .addComponent(lblCliente_EstCivil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGeneroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoCivilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente_TelFixo)
                    .addComponent(lblCliente_Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelFixCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        pnlEndereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCliente_End.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCliente_End.setText("Endereço");

        lblCliente_CEP.setText("CEP:");

        try {
            txtCEPCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEPCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCEPCliente.setName("CEP"); // NOI18N

        lblCliente_Log.setText("Logradouro:");

        txtLogCliente.setName("Logradouro"); // NOI18N
        txtLogCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogClienteActionPerformed(evt);
            }
        });
        txtLogCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLogClienteKeyTyped(evt);
            }
        });

        lblCliente_Num.setText("Nº:");

        txtNumCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtNumCliente.setName("Número"); // NOI18N
        txtNumCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumClienteKeyTyped(evt);
            }
        });

        lblCliente_Compl.setText("Complemento:");

        txtComplementoCliente.setName("Complemento"); // NOI18N
        txtComplementoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComplementoClienteKeyTyped(evt);
            }
        });

        lblCliente_Bairro.setText("Bairro:");

        txtBairroCliente.setName("Bairro"); // NOI18N
        txtBairroCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroClienteKeyTyped(evt);
            }
        });

        lblCliente_Cid.setText("Cidade:");

        txtCidadeCliente.setName("Cidade"); // NOI18N
        txtCidadeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCidadeClienteKeyTyped(evt);
            }
        });

        lblCliente_UF.setText("UF:");

        cboUFCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cboUFCliente.setName("UF"); // NOI18N
        cboUFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUFClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEnderecoLayout = new javax.swing.GroupLayout(pnlEndereco);
        pnlEndereco.setLayout(pnlEnderecoLayout);
        pnlEnderecoLayout.setHorizontalGroup(
            pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_CEP)
                            .addComponent(txtCEPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_Log)
                            .addComponent(txtLogCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblCliente_Num)
                                .addGap(22, 22, 22))
                            .addComponent(txtNumCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                                .addComponent(lblCliente_Compl)
                                .addGap(0, 145, Short.MAX_VALUE))
                            .addComponent(txtComplementoCliente)))
                    .addComponent(lblCliente_End)
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_Bairro)
                            .addComponent(txtBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCliente_Cid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_UF)
                            .addComponent(cboUFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlEnderecoLayout.setVerticalGroup(
            pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addComponent(lblCliente_End)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente_CEP)
                            .addComponent(lblCliente_Log))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCEPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente_Bairro)
                            .addComponent(lblCliente_Cid)))
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                                .addComponent(lblCliente_Num)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                                .addComponent(lblCliente_Compl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComplementoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(lblCliente_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboUFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAtualizar.setBackground(new java.awt.Color(183, 68, 30));
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setBorderPainted(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        btnAtualizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAtualizarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlDadosBasicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadosBasicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstadoCivilClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoCivilClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoCivilClienteActionPerformed

    private void txtLogClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogClienteActionPerformed

    private void cboUFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUFClienteActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_cboUFClienteActionPerformed

    private void btnAtualizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAtualizarKeyPressed

    }//GEN-LAST:event_btnAtualizarKeyPressed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        /**
         * Cria uma instância da classe Validador para validar os campos de
         * texto. Em seguida, verifica se ocorreram erros durante a validação.
         */
        Validador validacao = new Validador();
        validacao.validarTexto(txtNomeCliente);
        validacao.validarTexto(txtCPFCliente);
        validacao.validarTexto(txtDtNascimentoCliente);
        validacao.validarTexto(txtGeneroCliente);
        validacao.validarTexto(txtEstadoCivilCliente);
        validacao.validarTexto(txtTelFixCliente);
        validacao.validarTexto(txtEmailCliente);
        validacao.validarTexto(txtCEPCliente);
        validacao.validarTexto(txtLogCliente);
        validacao.validarTexto(txtNumCliente);
        validacao.validarTexto(txtComplementoCliente);
        validacao.validarTexto(txtBairroCliente);
        validacao.validarTexto(txtCidadeCliente);
        validacao.validarSelecaoComboBox(cboUFCliente);

        /**
         * Se houver erros, obtém as mensagens de erro e o exibe na tela. Caso
         * contrário, exibe uma mensagem de cadastro bem-sucedido.
         */
        if (validacao.hasErro()) {
            String mensagensDeErro = validacao.getMensagensErro();
            JOptionPane.showMessageDialog(rootPane, mensagensDeErro);

        } else {
            
            int id = obj.getIdCliente();
            String nome = txtNomeCliente.getText();
            String cpf = txtCPFCliente.getText();

            java.util.Date dataFormatada = new java.util.Date(Date.parse(txtDtNascimentoCliente.getText()));

            SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");

            Date dtNascimentoCliente = Date.valueOf(formatador.format(dataFormatada));

            String genero = txtGeneroCliente.getText();
            String estadoCivil = txtEstadoCivilCliente.getText();
            String telefone = txtTelFixCliente.getText();
            String email = txtEmailCliente.getText();
            String cep = txtCEPCliente.getText();
            String logradouro = txtLogCliente.getText();
            String numero = txtNumCliente.getText();
            String complemento = txtComplementoCliente.getText();
            String bairro = txtBairroCliente.getText();
            String cidade = txtCidadeCliente.getText();
            String uf = cboUFCliente.getSelectedItem().toString();

//            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//            Date dataNascimento = Date.valueOf(sdf.format(dtNascimentoCliente));
            
            Cliente cliente = new Cliente(id, nome, cpf, dtNascimentoCliente, genero, estadoCivil, telefone,
                    email, cep, logradouro, numero, complemento, bairro, cidade, uf);

            // Verifica se existe algum cadastro com o CPF informado pelo usuário.
//            boolean cadastroExiste = ClienteDAO.verificarExistenciaCadastroCPF(cpf);

            /**
             * Se existir um cadastro para o CPF informado, ele emite uma
             * mensagem informando a existência desse cadastro. Caso contrário,
             * ele permite o novo cadastro ser gravado.
             */
//            if (cadastroExiste == true) {
//
//                JOptionPane.showMessageDialog(rootPane, "Cliente já cadastrado no sistema!");
//
//            } else {

                boolean retorno = ClienteDAO.alterar(cliente);

                if (retorno == true) {
                    JOptionPane.showMessageDialog(rootPane, "Cadastro efetuado com sucesso!");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha no cadastro!");
                }

//            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtNomeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeClienteKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtNomeCliente. Por fim,
         * chama o método limitarEntradaTexto para restringir a entrada de texto
         * no campo txtNomeCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtNomeCliente, 50);
        validacao.limitarEntradaTexto(evt, txtNomeCliente);
    }//GEN-LAST:event_txtNomeClienteKeyTyped

    private void txtGeneroClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeneroClienteKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtGeneroCliente. Por fim,
         * chama o método limitarEntradaTexto para restringir a entrada de texto
         * no campo txtGeneroCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtGeneroCliente, 20);
        validacao.limitarEntradaTexto(evt, txtGeneroCliente);
    }//GEN-LAST:event_txtGeneroClienteKeyTyped

    private void txtEstadoCivilClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoCivilClienteKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtEstadoCivilCliente. Por
         * fim, chama o método limitarEntradaTexto para restringir a entrada de
         * texto no campo txtEstadoCivilCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtEstadoCivilCliente, 20);
        validacao.limitarEntradaTexto(evt, txtEstadoCivilCliente);
    }//GEN-LAST:event_txtEstadoCivilClienteKeyTyped

    private void txtEmailClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailClienteKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtEmailCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtEmailCliente, 50);
    }//GEN-LAST:event_txtEmailClienteKeyTyped

    private void txtLogClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLogClienteKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtLogCliente. Por fim, chama
         * o método limitarEntradaTexto para restringir a entrada de texto no
         * campo txtLogCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtLogCliente, 50);
        validacao.limitarEntradaTexto(evt, txtLogCliente);
    }//GEN-LAST:event_txtLogClienteKeyTyped

    private void txtNumClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumClienteKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtNumCliente. Por fim, chama
         * o método limitarEntradaNumerica para restringir a entrada de números
         * no campo txtNumCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtNumCliente, 10);
        validacao.limitarEntradaNumerica(evt, txtNumCliente);
    }//GEN-LAST:event_txtNumClienteKeyTyped

    private void txtComplementoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoClienteKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtComplementoCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtComplementoCliente, 30);
    }//GEN-LAST:event_txtComplementoClienteKeyTyped

    private void txtBairroClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroClienteKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtBairroCliente. Por fim,
         * chama o método limitarEntradaTexto para restringir a entrada de texto
         * no campo txtBairroCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtBairroCliente, 30);
        validacao.limitarEntradaTexto(evt, txtBairroCliente);
    }//GEN-LAST:event_txtBairroClienteKeyTyped

    private void txtCidadeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeClienteKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtCidadeCliente. Por fim,
         * chama o método limitarEntradaTexto para restringir a entrada de texto
         * no campo txtCidadeCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtCidadeCliente, 50);
        validacao.limitarEntradaTexto(evt, txtCidadeCliente);
    }//GEN-LAST:event_txtCidadeClienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarCadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JComboBox<String> cboUFCliente;
    private javax.swing.JLabel lblCliente_Bairro;
    private javax.swing.JLabel lblCliente_CEP;
    private javax.swing.JLabel lblCliente_CPF;
    private javax.swing.JLabel lblCliente_Cid;
    private javax.swing.JLabel lblCliente_Compl;
    private javax.swing.JLabel lblCliente_Email;
    private javax.swing.JLabel lblCliente_End;
    private javax.swing.JLabel lblCliente_EstCivil;
    private javax.swing.JLabel lblCliente_Genero;
    private javax.swing.JLabel lblCliente_ID;
    private javax.swing.JLabel lblCliente_Log;
    private javax.swing.JLabel lblCliente_Nome;
    private javax.swing.JLabel lblCliente_Num;
    private javax.swing.JLabel lblCliente_TelFixo;
    private javax.swing.JLabel lblCliente_UF;
    private javax.swing.JLabel lblCliente_dtNasc;
    private javax.swing.JLabel lblDadosBasicos;
    private javax.swing.JPanel pnlDadosBasicos;
    private javax.swing.JPanel pnlEndereco;
    private javax.swing.JTextField txtBairroCliente;
    private javax.swing.JFormattedTextField txtCEPCliente;
    private javax.swing.JFormattedTextField txtCPFCliente;
    private javax.swing.JTextField txtCidadeCliente;
    private javax.swing.JTextField txtComplementoCliente;
    private javax.swing.JFormattedTextField txtDtNascimentoCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEstadoCivilCliente;
    private javax.swing.JTextField txtGeneroCliente;
    private javax.swing.JTextField txtLogCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JFormattedTextField txtNumCliente;
    private javax.swing.JFormattedTextField txtTelFixCliente;
    // End of variables declaration//GEN-END:variables
}
