package br.sp.eml.projects.padariabythecode.view;

import br.sp.eml.projects.padariabythecode.dao.VendaDAO;
import br.sp.eml.projects.padariabythecode.model.Cliente;
import br.sp.eml.projects.padariabythecode.model.ItemVenda;
import br.sp.eml.projects.padariabythecode.model.Produto;
import br.sp.eml.projects.padariabythecode.model.Venda;
import br.sp.eml.projects.padariabythecode.utils.Utils;
import br.sp.eml.projects.padariabythecode.utils.Validador;

import java.text.DecimalFormat;
//import java.time.LocalDateTime;
//import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.sp.eml.projects.padariabythecode.secondscreens.TelaConfirmacaoPedido;
import br.sp.eml.projects.padariabythecode.secondscreens.TelaListagemClientes;
import br.sp.eml.projects.padariabythecode.secondscreens.TelaListagemProdutos;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JTable;

/**
 *
 * @author emlel
 */
public class TelaPrincipalVendas extends javax.swing.JFrame {
    
    public Cliente clienteVenda;
    public Produto produtoVenda;

    /**
     * Construtor da classe TelaPrincipalVendas. Inicializa os componentes
     * gráficos gerados automaticamente. Em seguida, define a posição da janela
     * ao centro da tela.
     */
    public TelaPrincipalVendas() {
        initComponents();
        setLocationRelativeTo(null);
//        Date dataAtual = new Date();
//        lblDataAtual.setText(dataAtual.toString());
    }
    
    public void preencherDadosCliente() {
        
        if (clienteVenda != null) {
            
            txtNomeCliente.setText(clienteVenda.getNomeCliente());
            txtCPF.setText(clienteVenda.getCpfCliente());
        }
        
    }
    
    public void preencherDadosProduto() {
        
        if (produtoVenda != null) {
            
            txtNomeProduto.setText(produtoVenda.getNomeProduto());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVendas = new javax.swing.JPanel();
        lblTituloVendas = new javax.swing.JLabel();
        pnlRodape = new javax.swing.JPanel();
        lblDataAtual = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        btnBuscarCliente = new javax.swing.JButton();
        btnRedirecionarTelaCadClientes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        btnBuscarNomeProduto = new javax.swing.JButton();
        txtQtdProduto = new javax.swing.JTextField();
        btnAdicionarProduto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaItensPedido = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnExcluirItemProduto = new javax.swing.JButton();
        btnAdicionarCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAdicionarPedido = new javax.swing.JButton();
        pnlCabecalho = new javax.swing.JPanel();
        btnNavBarClientes = new javax.swing.JButton();
        btnNavBarRelatorio = new javax.swing.JButton();
        btnNavBarProdutos = new javax.swing.JButton();
        lblNomePadaria = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        pnlResumoDoPedido = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnFinalizarPedido = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        pnlDadosCliente = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        lblCPFCliente = new javax.swing.JLabel();
        lblTelefoneCliente = new javax.swing.JLabel();
        lblNumeroPedido = new javax.swing.JLabel();
        lblDataPedido = new javax.swing.JLabel();
        lblValorTotalPedido = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIDCliente = new javax.swing.JLabel();
        mnuBar = new javax.swing.JMenuBar();
        mnuArquivos = new javax.swing.JMenu();
        mnuItemCadatroClientes = new javax.swing.JMenuItem();
        mnuItemCadastroProdutos = new javax.swing.JMenuItem();
        mnuItemRelatorioVendas = new javax.swing.JMenuItem();
        mnuEditar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlVendas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloVendas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloVendas.setText("VENDAS");

        javax.swing.GroupLayout pnlVendasLayout = new javax.swing.GroupLayout(pnlVendas);
        pnlVendas.setLayout(pnlVendasLayout);
        pnlVendasLayout.setHorizontalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVendasLayout.setVerticalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRodape.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDataAtual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDataAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataAtual.setText("23/09/2023");
        lblDataAtual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlRodapeLayout = new javax.swing.GroupLayout(pnlRodape);
        pnlRodape.setLayout(pnlRodapeLayout);
        pnlRodapeLayout.setHorizontalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRodapeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlRodapeLayout.setVerticalGroup(
            pnlRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nome do Cliente:");

        txtNomeCliente.setName("Nome Cliente"); // NOI18N
        txtNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeClienteKeyTyped(evt);
            }
        });

        jLabel2.setText("CPF:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setName("CPF Cliente"); // NOI18N

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnRedirecionarTelaCadClientes.setText("Cadastrar Novo Cliente");
        btnRedirecionarTelaCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedirecionarTelaCadClientesActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome do Produto:");

        txtNomeProduto.setName("Nome do Produto"); // NOI18N
        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });
        txtNomeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeProdutoKeyTyped(evt);
            }
        });

        btnBuscarNomeProduto.setText("Buscar");
        btnBuscarNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNomeProdutoActionPerformed(evt);
            }
        });

        txtQtdProduto.setName("Quantidade Produto"); // NOI18N
        txtQtdProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtdProdutoKeyTyped(evt);
            }
        });

        btnAdicionarProduto.setText("Adicionar Produto");
        btnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblListaItensPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Produto", "Nome do Produto", "Qtd", "Valor Unitário", "Valor Total"
            }
        ));
        tblListaItensPedido.setName(""); // NOI18N
        jScrollPane1.setViewportView(tblListaItensPedido);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Lista de Itens:");

        btnExcluirItemProduto.setText("Excluir Item");
        btnExcluirItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirItemProduto))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnExcluirItemProduto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnAdicionarCliente.setText("Adicionar Cliente");
        btnAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade:");

        btnAdicionarPedido.setText("Adicionar Pedido");
        btnAdicionarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRedirecionarTelaCadClientes))))
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscarNomeProduto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(txtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdicionarProduto)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdicionarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(btnRedirecionarTelaCadClientes)
                    .addComponent(btnAdicionarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarNomeProduto)
                    .addComponent(txtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtQtdProduto.getAccessibleContext().setAccessibleName("");

        pnlCabecalho.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNavBarClientes.setText("Clientes");
        btnNavBarClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNavBarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavBarClientesActionPerformed(evt);
            }
        });

        btnNavBarRelatorio.setText("Relatório de Vendas");
        btnNavBarRelatorio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNavBarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavBarRelatorioActionPerformed(evt);
            }
        });

        btnNavBarProdutos.setText("Produtos");
        btnNavBarProdutos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNavBarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavBarProdutosActionPerformed(evt);
            }
        });

        lblNomePadaria.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNomePadaria.setText("By The Code Bakery");

        lblLogotipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogotipo.setText("LOGO");
        lblLogotipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblLogotipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlCabecalhoLayout = new javax.swing.GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomePadaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNavBarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavBarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavBarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCabecalhoLayout.setVerticalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomePadaria))
                .addContainerGap())
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNavBarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavBarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavBarClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlResumoDoPedido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("RESUMO DO PEDIDO:");

        btnFinalizarPedido.setText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        btnCancelarPedido.setText("Cancelar Pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        pnlDadosCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeCliente.setText("Cliente:");

        lblCPFCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCPFCliente.setText("CPF:");

        lblTelefoneCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefoneCliente.setText("Telefone:");

        lblNumeroPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumeroPedido.setText("Nº PEDIDO: 0000");

        lblDataPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataPedido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDataPedido.setText("23/09/2023 21:19");

        lblValorTotalPedido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblValorTotalPedido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorTotalPedido.setText("R$ 0,00");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Valor Total:");

        lblIDCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIDCliente.setText("ID Cliente:");

        javax.swing.GroupLayout pnlDadosClienteLayout = new javax.swing.GroupLayout(pnlDadosCliente);
        pnlDadosCliente.setLayout(pnlDadosClienteLayout);
        pnlDadosClienteLayout.setHorizontalGroup(
            pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosClienteLayout.createSequentialGroup()
                        .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosClienteLayout.createSequentialGroup()
                                .addComponent(lblNumeroPedido)
                                .addGap(18, 18, 18)
                                .addComponent(lblDataPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosClienteLayout.createSequentialGroup()
                                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeCliente)
                                    .addComponent(lblCPFCliente)
                                    .addComponent(lblTelefoneCliente))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                        .addComponent(lblIDCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlDadosClienteLayout.setVerticalGroup(
            pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroPedido)
                    .addComponent(lblDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIDCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCPFCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTelefoneCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblValorTotalPedido))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout pnlResumoDoPedidoLayout = new javax.swing.GroupLayout(pnlResumoDoPedido);
        pnlResumoDoPedido.setLayout(pnlResumoDoPedidoLayout);
        pnlResumoDoPedidoLayout.setHorizontalGroup(
            pnlResumoDoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResumoDoPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResumoDoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDadosCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResumoDoPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106)))
                .addContainerGap())
        );
        pnlResumoDoPedidoLayout.setVerticalGroup(
            pnlResumoDoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResumoDoPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        mnuArquivos.setText("Arquivos");

        mnuItemCadatroClientes.setText("Cadastro Clientes");
        mnuItemCadatroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadatroClientesActionPerformed(evt);
            }
        });
        mnuArquivos.add(mnuItemCadatroClientes);

        mnuItemCadastroProdutos.setText("Cadastro Produtos");
        mnuItemCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroProdutosActionPerformed(evt);
            }
        });
        mnuArquivos.add(mnuItemCadastroProdutos);

        mnuItemRelatorioVendas.setText("Relatório de Vendas");
        mnuItemRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRelatorioVendasActionPerformed(evt);
            }
        });
        mnuArquivos.add(mnuItemRelatorioVendas);

        mnuBar.add(mnuArquivos);

        mnuEditar.setText("Editar");
        mnuBar.add(mnuEditar);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlResumoDoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlResumoDoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroProdutosActionPerformed
        /**
         * Instancia um novo objeto da classe TelaProdutos através do menubar e
         * o torna visível. Em seguida, oculta a janela atual.
         */
        new TelaProdutos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItemCadastroProdutosActionPerformed

    private void btnAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarClienteActionPerformed
        /**
         * Método de validação somente para a validação de campos e apresentação
         * na tela estática.
         *
         * O método atual só irá receber os parâmetros dos campos TextField de
         * Nome e CPF e apresentá-los na tela.
         *
         * Quando o CRUD for implementado o mesmo deverá resgatar tais
         * informações como idCliente, nomeCliente, cpfCliente e etc, do Banco
         * de Dados.
         */

        //Instâncio um objeto da classe Utils
        Utils utilitario = new Utils();

        //Instâncio um objeto da classe Validador e valido os campos txtNomeCliente e txtCPF.
        Validador validacao = new Validador();
        validacao.validarTexto(txtNomeCliente);
        validacao.validarTexto(txtCPF);

        //Verifico se houve algum erro nessa validação
        if (validacao.hasErro()) {
            //Se houver erro, busco as mensagens de erro geradas e as exibo na tela
            String mensagensDeErro = validacao.getMensagensErro();
            JOptionPane.showMessageDialog(rootPane, mensagensDeErro);
            
        } else {

            /**
             * Se não houver erro, exibo os valores da entrada nos labels
             * lblNomeCliente e lblCPFCliente e desabilito o botão
             * btnAdicionarCliente.
             */
            lblIDCliente.setText("ID Cliente: " + clienteVenda.getIdCliente());
            lblNomeCliente.setText("Cliente: " + clienteVenda.getNomeCliente());
            lblCPFCliente.setText("CPF: " + clienteVenda.getCpfCliente());
            lblTelefoneCliente.setText("Telefone: " + clienteVenda.getTelefoneCliente());
            
            utilitario.desabilitarBotoes(btnAdicionarCliente);
        }

    }//GEN-LAST:event_btnAdicionarClienteActionPerformed

    private void btnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoActionPerformed

        //Instâncio um objeto da classe Validador e valido os campos txtNomeProduto e txtQtdProduto.
        Validador validacao = new Validador();
        validacao.validarTexto(txtNomeProduto);
        validacao.validarNumero(txtQtdProduto);

        //Verifico se houve algum erro nessa validação
        if (validacao.hasErro()) {
            //Se houver erro, busco as mensagens de erro geradas e as exibo na tela
            String mensagensDeErro = validacao.getMensagensErro();
            JOptionPane.showMessageDialog(rootPane, mensagensDeErro);
            
        } else {

            //Caso contrário, instâncio um objeto da clase DecimalFormat e aplico a máxima de apenas 2 dígitos depois da vírgula
            DecimalFormat formatarNumero = new DecimalFormat();
            formatarNumero.setMaximumFractionDigits(2);

            //Declaro variáveis auxiliares para cada campo da nova linha na tabela
            int qtdProd = Integer.parseInt(txtQtdProduto.getText());

            //Converto essas variáveis para Strings
            String codigoProduto = String.valueOf(produtoVenda.getIdProduto());
            String nomeProduto = produtoVenda.getNomeProduto();
            String qtdProduto = txtQtdProduto.getText();
            String valorUnitarioProduto = String.valueOf(formatarNumero.format(produtoVenda.getPrecoProduto()));
            String valorTotalItensProduto = String.valueOf(formatarNumero.format(qtdProd * produtoVenda.getPrecoProduto()));
            
            DefaultTableModel modelo = (DefaultTableModel) tblListaItensPedido.getModel();

            //Adiciono uma linha à tabela
            modelo.addRow(new String[]{
                codigoProduto,
                nomeProduto,
                qtdProduto,
                valorUnitarioProduto,
                valorTotalItensProduto
            });
            
        }

    }//GEN-LAST:event_btnAdicionarProdutoActionPerformed
    
    private void atualizarValorTotalPedido() {
        
        DecimalFormat formatarNumero = new DecimalFormat();
        formatarNumero.setMaximumFractionDigits(2);
        
        double pedidoValorTotal = calcularValorTotalPedido(tblListaItensPedido);

        //Exibo o valor total do pedido no label lblValorTotalPedido, depois de o formatar e o converter para String.
        lblValorTotalPedido.setText("R$ " + String.valueOf(formatarNumero.format(pedidoValorTotal)).replace(".", ","));
    }
    
    public double calcularValorTotalPedido(JTable tabela) {
        
        DecimalFormat formatarNumero = new DecimalFormat();
        formatarNumero.setMaximumFractionDigits(2);
        
        double produtoValor, pedidoValorTotal = 0;
        int produtoQuantidade;
        
        for (int i = 0; i < tabela.getRowCount(); i++) {

            //Busco o valor da linha i e coluna 3 (Valor Unitário) da tabela, substituo as vírgulas por pontos e converto o valor de String para double, atribuindo à variável produtoValor.
            produtoValor = Double.parseDouble(String.valueOf(tabela.getModel().getValueAt(i, 3)).replace(",", "."));
            //Busco o valor da linha i e coluna 2 (Qtd) da tabela, converto o valor de String para int, atribuindo à variável produtoQuantidade.
            produtoQuantidade = Integer.parseInt(String.valueOf(tabela.getModel().getValueAt(i, 2)));

            //Realizo o cálculo do valor total do pedido
            pedidoValorTotal += (produtoQuantidade * produtoValor);
        }
        
        return pedidoValorTotal;
    }
    

    private void btnExcluirItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemProdutoActionPerformed

        //Declaro uma variável auxiliar para resgatar uma linha selecionada da tabela tblListaItensPedido
        int linhaSelecionada = tblListaItensPedido.getSelectedRow();

        //Instâncio um objeto da classe DefaultTableModel para resgatar o modelo da tabela tblListaItensPedido
        DefaultTableModel modelo = (DefaultTableModel) tblListaItensPedido.getModel();

        //Verifico se o índice da linha selecionada é maior ou igual a 0
        if (linhaSelecionada >= 0) {
            modelo.removeRow(linhaSelecionada); //Removo a linha selecionada se for maior ou igual a 0
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!"); //Solicito a seleção de uma linha, caso seja menor que 0
        }

    }//GEN-LAST:event_btnExcluirItemProdutoActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void btnNavBarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavBarClientesActionPerformed
        /**
         * Instancia um novo objeto da classe TelaCadastroCliente e o torna
         * visível. Em seguida, oculta a janela atual.
         */
        new TelaCadastroCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNavBarClientesActionPerformed

    private void btnNavBarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavBarProdutosActionPerformed
        /**
         * Instancia um novo objeto da classe TelaProdutos e o torna visível. Em
         * seguida, oculta a janela atual.
         */
        new TelaProdutos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNavBarProdutosActionPerformed

    private void btnNavBarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavBarRelatorioActionPerformed
        /**
         * Instancia um novo objeto da classe TelaRelatorio e o torna visível.
         * Em seguida, oculta a janela atual.
         */
        new TelaRelatorio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNavBarRelatorioActionPerformed

    private void btnAdicionarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPedidoActionPerformed

        /**
         * Esse botão deverá, quando implementado o CRUD, criar uma lista com
         * dados do cliente, lista de produtos e valorTotalVenda para ser
         * finalmente enviado ao banco de dados com o botão finalizarPedido. No
         * momento os valores são estáticos.
         *
         */
        //Intâncio um objeto da classe Validador e valido os campos txtNomeCliente, txtCPF, txtNomeProduto, txtQtdProduto e tblListaItensPedido.
        Validador validacao = new Validador();
        validacao.validarTexto(txtNomeCliente);
        validacao.validarTexto(txtCPF);
        validacao.validarTexto(txtNomeProduto);
        validacao.validarNumero(txtQtdProduto);
        validacao.validarPreenchimentoTabela(tblListaItensPedido);

        //Se houver erro, busco as mensagens de erro geradas e as exibo na tela
        if (validacao.hasErro()) {
            String mensagensDeErro = validacao.getMensagensErro();
            JOptionPane.showMessageDialog(rootPane, mensagensDeErro);
        } else {

            //Se não houver erro, instâncio um objeto da classe Utils, desabilito os botões btnAdicionarProduto e btnExcluirItemProduto e chamo o método atualizarValorTotalPedido.
            Utils utilitario = new Utils();
            utilitario.desabilitarBotoes(btnAdicionarProduto);
            utilitario.desabilitarBotoes(btnExcluirItemProduto);
            atualizarValorTotalPedido();
        }

    }//GEN-LAST:event_btnAdicionarPedidoActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed

        /**
         * Além de realizar o insert do pedido no banco de dados o botão
         * btnFinalizarPedido irá chamar a telinha de confirmação de pedido.
         *
         * Como o banco de dados ainda não está implementado, o botão apenas
         * habilita a TelaConfirmacaoPedido e desabilita a TelaPrincipalVendas.
         */
        //Resgato os produtos
        ArrayList<ItemVenda> listaItens = new ArrayList<ItemVenda>();
        
        if (tblListaItensPedido.getRowCount() > 0) {
            
            for (int i = 0; i < tblListaItensPedido.getRowCount(); i++) {
                ItemVenda item = new ItemVenda();
                
                item.setIdProduto(Integer.parseInt(tblListaItensPedido.getValueAt(i, 0).toString()));
                item.setQtdProduto(Integer.parseInt(tblListaItensPedido.getValueAt(i, 2).toString()));
                item.setValorUnitarioItem(Double.parseDouble(tblListaItensPedido.getValueAt(i, 3).toString()));

                //Adiciono o objeto à listaItens
                listaItens.add(item);
                
            }
        }
        
        SimpleDateFormat formatadorDatas = new SimpleDateFormat("dd/MM/yyyy");
        
        Date dataAtual = new Date();
//        String dataAtualFormatada = formatadorDatas.format(dataAtual);
        
        double valorTotalVenda = calcularValorTotalPedido(tblListaItensPedido);
        int idCliente = clienteVenda.getIdCliente();
        
        Venda objVenda = new Venda();
        objVenda.setDataVenda(dataAtual);
        objVenda.setValorTotalVenda(valorTotalVenda);
        objVenda.setIdClienteVenda(idCliente);
        objVenda.setListaProdutos(listaItens);
        
        boolean retorno = VendaDAO.cadastrarVenda(objVenda);
        
        if (retorno == true) {
            JOptionPane.showMessageDialog(rootPane, "Venda efetuada com sucesso!");
            
            new TelaConfirmacaoPedido().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Falha na venda!");
        }
        

    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed

        //Instâncio um objeto da classe Utils e utilizo os métodos limparCampos e limparTabela para limpar o pnlPrincipal e tblListaItensPedido.
        Utils utilitario = new Utils();
        utilitario.limparCampos(pnlPrincipal);
        utilitario.limparTabela(tblListaItensPedido);

        //Retorno os labels do pnlResumoDoPedido para o seu estado inicial.
        lblNomeCliente.setText("Cliente: ");
        lblCPFCliente.setText("CPF: ");
        lblTelefoneCliente.setText("Telefone: ");
        lblValorTotalPedido.setText("R$ 0,00");

        //Habilito os botões btnAdicionarCliente, btnAdicionarProduto e btnExcluirItemProduto novamente.
        utilitario.habilitarBotoes(btnAdicionarCliente);
        utilitario.habilitarBotoes(btnAdicionarProduto);
        utilitario.habilitarBotoes(btnExcluirItemProduto);
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void btnRedirecionarTelaCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedirecionarTelaCadClientesActionPerformed
        /**
         * Instância um novo objeto da classe TelaCadastroCliente e o torna
         * visível. Em seguida, oculta a janela atual.
         */
        new TelaCadastroCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRedirecionarTelaCadClientesActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        //Instância um novo objeto da classe TelaListagemClientes e o torna visível.
        new TelaListagemClientes(this).setVisible(true);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNomeProdutoActionPerformed
        //Instância um novo objeto da classe TelaListagemProdutos e o torna visível.
        new TelaListagemProdutos(this).setVisible(true);
    }//GEN-LAST:event_btnBuscarNomeProdutoActionPerformed

    private void mnuItemCadatroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadatroClientesActionPerformed
        /**
         * Instância um novo objeto da classe TelaCadastroCliente através do
         * menubar e o torna visível. Em seguida, oculta a janela atual.
         */
        new TelaCadastroCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItemCadatroClientesActionPerformed

    private void mnuItemRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRelatorioVendasActionPerformed
        /**
         * Instância um novo objeto da classe TelaRelatorio através do menubar e
         * o torna visível. Em seguida, oculta a janela atual.
         */
        new TelaRelatorio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuItemRelatorioVendasActionPerformed

    private void txtNomeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeClienteKeyTyped
        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtNomeCliente.
         *
         * Por fim, chama o método limitarEntradaTexto para restringir a entrada
         * de texto no campo txtNomeCliente.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtNomeCliente, 50);
        validacao.limitarEntradaTexto(evt, txtNomeCliente);
    }//GEN-LAST:event_txtNomeClienteKeyTyped

    private void txtQtdProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdProdutoKeyTyped
        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarEntradaNumerica para restringir a
         * entrada de números no campo txtQtdProduto.
         *
         * Por fim, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtQtdProduto.
         */
        Validador validacao = new Validador();
        validacao.limitarEntradaNumerica(evt, txtQtdProduto);
        validacao.limitarQuantidadeCaracteres(evt, txtQtdProduto, 5);
    }//GEN-LAST:event_txtQtdProdutoKeyTyped

    private void txtNomeProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdutoKeyTyped

        /**
         * Cria uma instância da classe Validador para realizar validações. Em
         * seguida, chama o método limitarQuantidadeCaracteres para limitar o
         * número de caracteres inseridos no campo txtNomeProduto.
         *
         * Por fim, chama o método limitarEntradaTexto para restringir a entrada
         * de texto no campo txtNomeProduto.
         */
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtNomeProduto, 50);
        validacao.limitarEntradaTexto(evt, txtNomeProduto);
    }//GEN-LAST:event_txtNomeProdutoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCliente;
    private javax.swing.JButton btnAdicionarPedido;
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarNomeProduto;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnExcluirItemProduto;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnNavBarClientes;
    private javax.swing.JButton btnNavBarProdutos;
    private javax.swing.JButton btnNavBarRelatorio;
    private javax.swing.JButton btnRedirecionarTelaCadClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPFCliente;
    private javax.swing.JLabel lblDataAtual;
    private javax.swing.JLabel lblDataPedido;
    private javax.swing.JLabel lblIDCliente;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomePadaria;
    private javax.swing.JLabel lblNumeroPedido;
    private javax.swing.JLabel lblTelefoneCliente;
    private javax.swing.JLabel lblTituloVendas;
    private javax.swing.JLabel lblValorTotalPedido;
    private javax.swing.JMenu mnuArquivos;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuEditar;
    private javax.swing.JMenuItem mnuItemCadastroProdutos;
    private javax.swing.JMenuItem mnuItemCadatroClientes;
    private javax.swing.JMenuItem mnuItemRelatorioVendas;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlDadosCliente;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlResumoDoPedido;
    private javax.swing.JPanel pnlRodape;
    private javax.swing.JPanel pnlVendas;
    private javax.swing.JTable tblListaItensPedido;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtQtdProduto;
    // End of variables declaration//GEN-END:variables
}
