/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.sp.eml.projects.padariabythecode.view;

import br.sp.eml.projects.padariabythecode.utils.Utils;
import br.sp.eml.projects.padariabythecode.utils.Validador;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import secondscreens.TelaEdit;
import secondscreens.TelaEditCadastro;

/**
 *
 * @author narum
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCabecalho = new javax.swing.JPanel();
        btnNavBarVendas = new javax.swing.JButton();
        btnNavBarRelatorio = new javax.swing.JButton();
        btnNavBarProdutos = new javax.swing.JButton();
        lblBTCBakery = new javax.swing.JLabel();
        lblLogotipo = new javax.swing.JLabel();
        pnlClientes = new javax.swing.JPanel();
        lblTituloClientes = new javax.swing.JLabel();
        pnlCadastroCliente = new javax.swing.JPanel();
        lblCadastro = new javax.swing.JLabel();
        pnlDadosBasicos = new javax.swing.JPanel();
        lblDadosBasicos = new javax.swing.JLabel();
        lblCliente_ID = new javax.swing.JLabel();
        lblCliente_CPF = new javax.swing.JLabel();
        txtCPFCliente = new javax.swing.JFormattedTextField();
        lblCliente_dtNasc = new javax.swing.JLabel();
        txtDtNascimentoCliente = new javax.swing.JFormattedTextField();
        lblCliente_Genero = new javax.swing.JLabel();
        txtGeneroCliente = new javax.swing.JTextField();
        lblCliente_EstCivil = new javax.swing.JLabel();
        txtEstadoCivilCliente = new javax.swing.JTextField();
        lblCliente_Nome = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblCliente_TelFixo = new javax.swing.JLabel();
        txtTelFixCliente = new javax.swing.JFormattedTextField();
        lblCliente_Celular = new javax.swing.JLabel();
        txtCelCliente = new javax.swing.JFormattedTextField();
        lblCliente_Email = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        pnlEndereco = new javax.swing.JPanel();
        lblCliente_End = new javax.swing.JLabel();
        lblCliente_CEP = new javax.swing.JLabel();
        txtCEPCliente = new javax.swing.JFormattedTextField();
        lblCliente_Log = new javax.swing.JLabel();
        txtLogCliente = new javax.swing.JTextField();
        lblCliente_Num = new javax.swing.JLabel();
        txtNumCliente = new javax.swing.JFormattedTextField();
        lblCliente_Compl = new javax.swing.JLabel();
        txtComplementoCliente = new javax.swing.JTextField();
        lblCliente_Bairro = new javax.swing.JLabel();
        txtBairroCliente = new javax.swing.JTextField();
        lblCliente_Cid = new javax.swing.JLabel();
        txtCidadeCliente = new javax.swing.JTextField();
        lblCliente_UF = new javax.swing.JLabel();
        txtUFCliente = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        pnlListaClientes = new javax.swing.JPanel();
        lblListaClientes = new javax.swing.JLabel();
        tblCadastoCliente = new javax.swing.JScrollPane();
        tblCadClientes = new javax.swing.JTable();
        pnlBuscarCliente = new javax.swing.JPanel();
        lblBuscarCliente = new javax.swing.JLabel();
        lblBuscaCliente_Nome = new javax.swing.JLabel();
        txtBuscaCliente_Nome = new javax.swing.JTextField();
        lblBuscaClienteCPF = new javax.swing.JLabel();
        txtBuscaCliente_CPF = new javax.swing.JFormattedTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblBuscaNome = new javax.swing.JLabel();
        lblBuscaCPF = new javax.swing.JLabel();
        lblBuscaDtNasc = new javax.swing.JLabel();
        lblBuscaTel = new javax.swing.JLabel();
        lblBuscaEnd = new javax.swing.JLabel();
        btnEditarCadastro = new javax.swing.JButton();
        btnLimparBusca = new javax.swing.JButton();
        pnlRodape1 = new javax.swing.JPanel();
        pnlDataAtual = new javax.swing.JLabel();
        mnuBar = new javax.swing.JMenuBar();
        mnuArquivos = new javax.swing.JMenu();
        mnuItemCadastroClientes = new javax.swing.JMenuItem();
        mnuItemCadastroProdutos = new javax.swing.JMenuItem();
        mnuItemRelatorioVendas = new javax.swing.JMenuItem();
        mnuEditar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCabecalho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCabecalho.setPreferredSize(new java.awt.Dimension(657, 63));

        btnNavBarVendas.setText("Vendas");
        btnNavBarVendas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNavBarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavBarVendasActionPerformed(evt);
            }
        });

        btnNavBarRelatorio.setText("Relatório de Vendas");
        btnNavBarRelatorio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNavBarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavBarRelatorioActionPerformed(evt);
            }
        });

        btnNavBarProdutos.setText("Produtos");
        btnNavBarProdutos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNavBarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavBarProdutosActionPerformed(evt);
            }
        });

        lblBTCBakery.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBTCBakery.setText("By The Code Bakery");
        lblBTCBakery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblLogotipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogotipo.setText("LOGO");
        lblLogotipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblLogotipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlCabecalhoLayout = new javax.swing.GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBTCBakery, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNavBarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavBarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavBarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCabecalhoLayout.setVerticalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNavBarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavBarProdutos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBTCBakery, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(lblLogotipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavBarVendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloClientes.setText("CLIENTES");

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCadastroCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCadastro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCadastro.setText("CADASTRO");

        pnlDadosBasicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDadosBasicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDadosBasicos.setText("Dados Básicos");

        lblCliente_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCliente_ID.setText("ID: 123");

        lblCliente_CPF.setText("CPF:");

        try {
            txtCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCPFCliente.setName("CPF Cliente"); // NOI18N
        txtCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFClienteActionPerformed(evt);
            }
        });

        lblCliente_dtNasc.setText("Data de Nascimento:");

        try {
            txtDtNascimentoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtNascimentoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDtNascimentoCliente.setName("Data de Nascimento"); // NOI18N

        lblCliente_Genero.setText("Gênero:");

        txtGeneroCliente.setName("Gênero"); // NOI18N
        txtGeneroCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGeneroClienteKeyTyped(evt);
            }
        });

        lblCliente_EstCivil.setText("Estado Civil:");

        txtEstadoCivilCliente.setName("Estado Civil"); // NOI18N
        txtEstadoCivilCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoCivilClienteActionPerformed(evt);
            }
        });
        txtEstadoCivilCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoCivilClienteKeyTyped(evt);
            }
        });

        lblCliente_Nome.setText("Nome do Cliente:");

        txtNomeCliente.setName("Nome do Cliente"); // NOI18N
        txtNomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeClienteKeyTyped(evt);
            }
        });

        lblCliente_TelFixo.setText("Telefone Fixo:");

        try {
            txtTelFixCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelFixCliente.setName("Telefone Fixo"); // NOI18N

        lblCliente_Celular.setText("Celular:");

        try {
            txtCelCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelCliente.setName("Celular"); // NOI18N

        lblCliente_Email.setText("E-mail:");

        txtEmailCliente.setName("Email"); // NOI18N
        txtEmailCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosBasicosLayout = new javax.swing.GroupLayout(pnlDadosBasicos);
        pnlDadosBasicos.setLayout(pnlDadosBasicosLayout);
        pnlDadosBasicosLayout.setHorizontalGroup(
            pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                        .addComponent(lblDadosBasicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCliente_ID))
                    .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_CPF)
                            .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCliente_TelFixo)
                            .addComponent(txtTelFixCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_dtNasc)
                            .addComponent(txtDtNascimentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCliente_Celular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCliente_Genero)
                                    .addComponent(txtGeneroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCliente_Email))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCliente_EstCivil))
                            .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCliente_Nome)
                    .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtEstadoCivilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosBasicosLayout.setVerticalGroup(
            pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosBasicosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosBasicosLayout.createSequentialGroup()
                            .addComponent(lblCliente_Celular)
                            .addGap(28, 28, 28)))
                    .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_ID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDadosBasicos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCliente_Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                                .addComponent(lblCliente_CPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                                .addComponent(lblCliente_dtNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDtNascimentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                                .addComponent(lblCliente_Genero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGeneroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstadoCivilCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                                .addComponent(lblCliente_EstCivil)
                                .addGap(28, 28, 28)))
                        .addGroup(pnlDadosBasicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosBasicosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblCliente_Email))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosBasicosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCliente_TelFixo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelFixCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(9, 9, 9))
        );

        pnlEndereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCliente_End.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCliente_End.setText("Endereço");

        lblCliente_CEP.setText("CEP:");

        try {
            txtCEPCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEPCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCEPCliente.setName("CEP"); // NOI18N

        lblCliente_Log.setText("Logradouro:");

        txtLogCliente.setName("Logradouro"); // NOI18N
        txtLogCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogClienteActionPerformed(evt);
            }
        });
        txtLogCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLogClienteKeyTyped(evt);
            }
        });

        lblCliente_Num.setText("Nº:");

        txtNumCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtNumCliente.setName("Número"); // NOI18N
        txtNumCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumClienteKeyTyped(evt);
            }
        });

        lblCliente_Compl.setText("Complemento:");

        txtComplementoCliente.setName("Complemento"); // NOI18N
        txtComplementoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComplementoClienteKeyTyped(evt);
            }
        });

        lblCliente_Bairro.setText("Bairro:");

        txtBairroCliente.setName("Bairro"); // NOI18N
        txtBairroCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroClienteKeyTyped(evt);
            }
        });

        lblCliente_Cid.setText("Cidade:");

        txtCidadeCliente.setName("Cidade"); // NOI18N
        txtCidadeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCidadeClienteKeyTyped(evt);
            }
        });

        lblCliente_UF.setText("UF:");

        txtUFCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        txtUFCliente.setName("UF"); // NOI18N
        txtUFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUFClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEnderecoLayout = new javax.swing.GroupLayout(pnlEndereco);
        pnlEndereco.setLayout(pnlEnderecoLayout);
        pnlEnderecoLayout.setHorizontalGroup(
            pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_CEP)
                            .addComponent(txtCEPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_Log)
                            .addComponent(txtLogCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblCliente_Num)
                                .addGap(22, 22, 22))
                            .addComponent(txtNumCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplementoCliente)
                            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                                .addComponent(lblCliente_Compl)
                                .addGap(147, 147, 147))))
                    .addComponent(lblCliente_End)
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_Bairro)
                            .addComponent(txtBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCliente_Cid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente_UF)
                            .addComponent(txtUFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7))
        );
        pnlEnderecoLayout.setVerticalGroup(
            pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addComponent(lblCliente_End)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente_CEP)
                            .addComponent(lblCliente_Log))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCEPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente_Bairro)
                            .addComponent(lblCliente_Cid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUFCliente)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnderecoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBairroCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCidadeCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                                .addComponent(lblCliente_Num)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                                .addComponent(lblCliente_Compl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtComplementoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(lblCliente_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroClienteLayout = new javax.swing.GroupLayout(pnlCadastroCliente);
        pnlCadastroCliente.setLayout(pnlCadastroClienteLayout);
        pnlCadastroClienteLayout.setHorizontalGroup(
            pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDadosBasicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                        .addComponent(lblCadastro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                        .addComponent(btnLimparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCadastroClienteLayout.setVerticalGroup(
            pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosBasicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnLimparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlListaClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblListaClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblListaClientes.setText("LISTA DE CLIENTES");

        tblCadClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone"
            }
        ));
        tblCadClientes.setToolTipText("");
        tblCadClientes.setColumnSelectionAllowed(true);
        tblCadClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblCadastoCliente.setViewportView(tblCadClientes);

        javax.swing.GroupLayout pnlListaClientesLayout = new javax.swing.GroupLayout(pnlListaClientes);
        pnlListaClientes.setLayout(pnlListaClientesLayout);
        pnlListaClientesLayout.setHorizontalGroup(
            pnlListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblCadastoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlListaClientesLayout.createSequentialGroup()
                        .addComponent(lblListaClientes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlListaClientesLayout.setVerticalGroup(
            pnlListaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblCadastoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBuscarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarCliente.setText("BUSCAR CLIENTE");

        lblBuscaCliente_Nome.setText("Nome Cliente:");

        txtBuscaCliente_Nome.setName("Nome Cliente"); // NOI18N
        txtBuscaCliente_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaCliente_NomeKeyTyped(evt);
            }
        });

        lblBuscaClienteCPF.setText("CPF:");

        try {
            txtBuscaCliente_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBuscaCliente_CPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscaCliente_CPF.setName("CPF Cliente"); // NOI18N
        txtBuscaCliente_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaCliente_CPFActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblBuscaNome.setText("Cliente:");

        lblBuscaCPF.setText("CPF:");

        lblBuscaDtNasc.setText("Data de Nascimento:");

        lblBuscaTel.setText("Telefone:");

        lblBuscaEnd.setText("Endereço:");

        btnEditarCadastro.setText("Editar Cadastro");
        btnEditarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCadastroActionPerformed(evt);
            }
        });

        btnLimparBusca.setText("Limpar Busca");
        btnLimparBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarClienteLayout = new javax.swing.GroupLayout(pnlBuscarCliente);
        pnlBuscarCliente.setLayout(pnlBuscarClienteLayout);
        pnlBuscarClienteLayout.setHorizontalGroup(
            pnlBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlBuscarClienteLayout.createSequentialGroup()
                        .addGroup(pnlBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscarCliente)
                            .addGroup(pnlBuscarClienteLayout.createSequentialGroup()
                                .addComponent(lblBuscaCliente_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscaCliente_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBuscaClienteCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscaCliente_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBuscaNome)
                            .addComponent(lblBuscaCPF)
                            .addComponent(lblBuscaDtNasc)
                            .addComponent(lblBuscaTel)
                            .addComponent(lblBuscaEnd)
                            .addGroup(pnlBuscarClienteLayout.createSequentialGroup()
                                .addComponent(btnLimparBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBuscarClienteLayout.setVerticalGroup(
            pnlBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscaCliente_Nome)
                    .addComponent(txtBuscaCliente_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(lblBuscaClienteCPF)
                    .addComponent(txtBuscaCliente_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBuscaNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBuscaCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBuscaDtNasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBuscaTel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBuscaEnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarCadastro)
                    .addComponent(btnLimparBusca))
                .addGap(12, 12, 12))
        );

        pnlRodape1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRodape1.setPreferredSize(new java.awt.Dimension(151, 36));

        pnlDataAtual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnlDataAtual.setText("26/09/2023");

        javax.swing.GroupLayout pnlRodape1Layout = new javax.swing.GroupLayout(pnlRodape1);
        pnlRodape1.setLayout(pnlRodape1Layout);
        pnlRodape1Layout.setHorizontalGroup(
            pnlRodape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRodape1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDataAtual)
                .addContainerGap())
        );
        pnlRodape1Layout.setVerticalGroup(
            pnlRodape1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        mnuArquivos.setText("Arquivos");

        mnuItemCadastroClientes.setText("Cadastro Cliente");
        mnuArquivos.add(mnuItemCadastroClientes);

        mnuItemCadastroProdutos.setText("Cadastro Produto");
        mnuArquivos.add(mnuItemCadastroProdutos);

        mnuItemRelatorioVendas.setText("Relatório de Vendas");
        mnuArquivos.add(mnuItemRelatorioVendas);

        mnuBar.add(mnuArquivos);

        mnuEditar.setText("Edit");
        mnuBar.add(mnuEditar);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
                    .addComponent(pnlRodape1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pnlClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlListaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRodape1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavBarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavBarRelatorioActionPerformed
        // TODO add your handling code here:
        new TelaRelatorio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNavBarRelatorioActionPerformed

    private void txtEstadoCivilClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoCivilClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoCivilClienteActionPerformed

    private void txtUFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUFClienteActionPerformed

    private void btnNavBarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavBarVendasActionPerformed
        // TODO add your handling code here:
        new TelaPrincipalVendas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNavBarVendasActionPerformed

    private void btnNavBarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavBarProdutosActionPerformed
        // TODO add your handling code here:
        new TelaProdutos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNavBarProdutosActionPerformed

    private void txtLogClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed

        Validador validacao = new Validador();
        validacao.validarTexto(txtBuscaCliente_Nome);
        validacao.validarTexto(txtBuscaCliente_CPF);

        if (validacao.hasErro()) {
            String mensagensDeErro = validacao.getMensagensErro();
            JOptionPane.showMessageDialog(rootPane, mensagensDeErro);
        } else {
            lblBuscaNome.setText("Cliente: " + txtBuscaCliente_Nome.getText());
            lblBuscaCPF.setText("CPF: " + txtBuscaCliente_CPF.getText());
        }

    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnEditarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCadastroActionPerformed

        //Abre nova tela para Editar Cadastro
        new TelaEditCadastro().setVisible(true);
    }//GEN-LAST:event_btnEditarCadastroActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        //Garante o preenchimento de todos os campos de cadastro, e se os campos estiverem vazios, pinta de vermelho.
        Validador validacao = new Validador();
        validacao.validarTexto(txtNomeCliente);
        validacao.validarTexto(txtCPFCliente);
        validacao.validarTexto(txtDtNascimentoCliente);
        validacao.validarTexto(txtGeneroCliente);
        validacao.validarTexto(txtEstadoCivilCliente);
        validacao.validarTexto(txtTelFixCliente);
        validacao.validarTexto(txtCelCliente);
        validacao.validarTexto(txtEmailCliente);
        validacao.validarTexto(txtCEPCliente);
        validacao.validarTexto(txtLogCliente);
        validacao.validarTexto(txtNumCliente);
        validacao.validarTexto(txtComplementoCliente);
        validacao.validarTexto(txtBairroCliente);
        validacao.validarTexto(txtCidadeCliente);
        //validacao.validarTexto(txtUFCliente);

        if (validacao.hasErro()) {
            String mensagensDeErro = validacao.getMensagensErro();
            JOptionPane.showMessageDialog(rootPane, mensagensDeErro);

        } else {

            JOptionPane.showMessageDialog(rootPane, "Cadastro efetuado com sucesso!");

            //Atribuindo valores digitados as variáveis para adicionar na lsita/tabela
            String nomeCliente = txtNomeCliente.getText();
            String cpfCliente = txtCPFCliente.getText();
            String telFixCliente = txtTelFixCliente.getText();

            DefaultTableModel tabelaCadCliente = (DefaultTableModel) tblCadClientes.getModel();

            //Adicionar uma linha à tabela
            tabelaCadCliente.addRow(new String[]{
                //idCLiente
                nomeCliente,
                cpfCliente,
                telFixCliente,});

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtBuscaCliente_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaCliente_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaCliente_CPFActionPerformed

    private void btnLimparBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparBuscaActionPerformed

        //"Seta" os valores vazios/em branco
        lblBuscaNome.setText("Cliente: ");
        lblBuscaCPF.setText("CPF: ");
        lblBuscaDtNasc.setText("Data de Nascimento: ");
        lblBuscaTel.setText("Telefone: ");
        lblBuscaEnd.setText("Endereço: ");
    }//GEN-LAST:event_btnLimparBuscaActionPerformed

    private void txtCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFClienteActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed

        //Chama o método Utils para limpar todos os campos quando apertar em "Limpar Campos"
        Utils limpar = new Utils();
        limpar.limparCampos(pnlDadosBasicos);
        limpar.limparCampos(pnlEndereco);

    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void txtNomeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeClienteKeyTyped
        
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtNomeCliente, 50);
        validacao.limitarEntradaTexto(evt, txtNomeCliente);
    }//GEN-LAST:event_txtNomeClienteKeyTyped

    private void txtGeneroClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeneroClienteKeyTyped
        
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtGeneroCliente, 20);
        validacao.limitarEntradaTexto(evt, txtGeneroCliente);
    }//GEN-LAST:event_txtGeneroClienteKeyTyped

    private void txtEstadoCivilClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoCivilClienteKeyTyped
        
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtEstadoCivilCliente, 20);
        validacao.limitarEntradaTexto(evt, txtEstadoCivilCliente);
    }//GEN-LAST:event_txtEstadoCivilClienteKeyTyped

    private void txtEmailClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailClienteKeyTyped
        
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtEmailCliente, 50);
    }//GEN-LAST:event_txtEmailClienteKeyTyped

    private void txtLogClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLogClienteKeyTyped
        
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtLogCliente, 50);
        validacao.limitarEntradaTexto(evt, txtLogCliente);
    }//GEN-LAST:event_txtLogClienteKeyTyped

    private void txtNumClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumClienteKeyTyped

        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtNumCliente, 10);
        validacao.limitarEntradaNumerica(evt, txtNumCliente);
    }//GEN-LAST:event_txtNumClienteKeyTyped

    private void txtBairroClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroClienteKeyTyped
        
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtBairroCliente, 30);
        validacao.limitarEntradaTexto(evt, txtBairroCliente);
    }//GEN-LAST:event_txtBairroClienteKeyTyped

    private void txtComplementoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoClienteKeyTyped
        
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtComplementoCliente, 30);
    }//GEN-LAST:event_txtComplementoClienteKeyTyped

    private void txtCidadeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeClienteKeyTyped
        
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtCidadeCliente, 50);
        validacao.limitarEntradaTexto(evt, txtCidadeCliente);
    }//GEN-LAST:event_txtCidadeClienteKeyTyped

    private void txtBuscaCliente_NomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaCliente_NomeKeyTyped
        
        Validador validacao = new Validador();
        validacao.limitarQuantidadeCaracteres(evt, txtBuscaCliente_Nome, 50);
        validacao.limitarEntradaTexto(evt, txtBuscaCliente_Nome);
    }//GEN-LAST:event_txtBuscaCliente_NomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditarCadastro;
    private javax.swing.JButton btnLimparBusca;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnNavBarProdutos;
    private javax.swing.JButton btnNavBarRelatorio;
    private javax.swing.JButton btnNavBarVendas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBTCBakery;
    private javax.swing.JLabel lblBuscaCPF;
    private javax.swing.JLabel lblBuscaClienteCPF;
    private javax.swing.JLabel lblBuscaCliente_Nome;
    private javax.swing.JLabel lblBuscaDtNasc;
    private javax.swing.JLabel lblBuscaEnd;
    private javax.swing.JLabel lblBuscaNome;
    private javax.swing.JLabel lblBuscaTel;
    private javax.swing.JLabel lblBuscarCliente;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCliente_Bairro;
    private javax.swing.JLabel lblCliente_CEP;
    private javax.swing.JLabel lblCliente_CPF;
    private javax.swing.JLabel lblCliente_Celular;
    private javax.swing.JLabel lblCliente_Cid;
    private javax.swing.JLabel lblCliente_Compl;
    private javax.swing.JLabel lblCliente_Email;
    private javax.swing.JLabel lblCliente_End;
    private javax.swing.JLabel lblCliente_EstCivil;
    private javax.swing.JLabel lblCliente_Genero;
    private javax.swing.JLabel lblCliente_ID;
    private javax.swing.JLabel lblCliente_Log;
    private javax.swing.JLabel lblCliente_Nome;
    private javax.swing.JLabel lblCliente_Num;
    private javax.swing.JLabel lblCliente_TelFixo;
    private javax.swing.JLabel lblCliente_UF;
    private javax.swing.JLabel lblCliente_dtNasc;
    private javax.swing.JLabel lblDadosBasicos;
    private javax.swing.JLabel lblListaClientes;
    private javax.swing.JLabel lblLogotipo;
    private javax.swing.JLabel lblTituloClientes;
    private javax.swing.JMenu mnuArquivos;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuEditar;
    private javax.swing.JMenuItem mnuItemCadastroClientes;
    private javax.swing.JMenuItem mnuItemCadastroProdutos;
    private javax.swing.JMenuItem mnuItemRelatorioVendas;
    private javax.swing.JPanel pnlBuscarCliente;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlCadastroCliente;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlDadosBasicos;
    private javax.swing.JLabel pnlDataAtual;
    private javax.swing.JPanel pnlEndereco;
    private javax.swing.JPanel pnlListaClientes;
    private javax.swing.JPanel pnlRodape1;
    private javax.swing.JTable tblCadClientes;
    private javax.swing.JScrollPane tblCadastoCliente;
    private javax.swing.JTextField txtBairroCliente;
    private javax.swing.JFormattedTextField txtBuscaCliente_CPF;
    private javax.swing.JTextField txtBuscaCliente_Nome;
    private javax.swing.JFormattedTextField txtCEPCliente;
    private javax.swing.JFormattedTextField txtCPFCliente;
    private javax.swing.JFormattedTextField txtCelCliente;
    private javax.swing.JTextField txtCidadeCliente;
    private javax.swing.JTextField txtComplementoCliente;
    private javax.swing.JFormattedTextField txtDtNascimentoCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEstadoCivilCliente;
    private javax.swing.JTextField txtGeneroCliente;
    private javax.swing.JTextField txtLogCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JFormattedTextField txtNumCliente;
    private javax.swing.JFormattedTextField txtTelFixCliente;
    private javax.swing.JComboBox<String> txtUFCliente;
    // End of variables declaration//GEN-END:variables
}
